#!/usr/bin/env python3
"""Render/check owner-controlled policy copies without overwriting local edits."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import tempfile
import os

OWNER = Path(__file__).resolve().parents[1]
EDITIONS = {"glide": "Glide HQ", "glide-obsidian": "Agent HQ", "glide-developer": "Glide HQ"}
CONTRACTS = {"memory-core.md": "Memory Core.md", "recovery-core.md": "Recovery Core.md"}
MARKER = "<!-- Generated by glide/tools/distribute_contracts.py; edit the owner contract. -->"


def safe_path(path):
    path = Path(os.path.abspath(path))
    if any(parent.is_symlink() for parent in (path, *path.parents)):
        raise ValueError("Generated contract paths must not contain symlinks")
    return path


def render(distribution):
    if distribution not in EDITIONS:
        raise ValueError("Unknown distribution")
    result = {}
    for source, filename in CONTRACTS.items():
        raw = (OWNER / "contracts" / source).read_bytes()
        text = raw.decode("utf-8").replace("{{HQ}}", EDITIONS[distribution])
        if "{{" in text or "}}" in text:
            raise ValueError("Unresolved contract placeholder")
        header = MARKER + "\n<!-- source: glide/contracts/" + source + "; sha256: " + hashlib.sha256(raw).hexdigest() + " -->\n"
        header += "<!-- generated-content-sha256: " + hashlib.sha256(text.encode()).hexdigest() + " -->\n\n"
        result["templates/" + EDITIONS[distribution] + "/Contracts/" + filename] = header + text
    return result


def check(target, distribution):
    target = safe_path(target)
    result = {"distribution": distribution, "missing": [], "changed": []}
    for relative, expected in render(distribution).items():
        path = safe_path(target / relative)
        if not path.exists():
            result["missing"].append(relative)
        elif path.read_text() != expected:
            result["changed"].append(relative)
    result["ok"] = not result["missing"] and not result["changed"]
    return result


def write(target, distribution):
    target = safe_path(target)
    rendered = render(distribution)
    # Preflight every target before writing any: generated provenance alone does
    # not authorize losing later human edits to a generated file.
    for relative in rendered:
        path = safe_path(target / relative)
        if path.exists():
            current = path.read_text()
            lines = current.splitlines(keepends=True)
            if not current.startswith(MARKER + "\n") or len(lines) < 4:
                raise ValueError("Refusing to overwrite an unowned contract: " + relative)
            match = re.fullmatch(r"<!-- generated-content-sha256: ([a-f0-9]{64}) -->\n", lines[2])
            body = "".join(lines[4:])
            if not match or hashlib.sha256(body.encode()).hexdigest() != match[1]:
                raise ValueError("Generated contract has local edits; review them: " + relative)
    for relative, text in rendered.items():
        path = safe_path(target / relative)
        if path.exists() and path.read_text() == text:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, temporary = tempfile.mkstemp(prefix=".contract-", dir=path.parent)
        try:
            with os.fdopen(fd, "w") as handle:
                handle.write(text)
            os.replace(temporary, path)
        finally:
            if Path(temporary).exists():
                Path(temporary).unlink()
    return check(target, distribution)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--distribution", choices=sorted(EDITIONS), required=True)
    parser.add_argument("--target", type=Path, required=True)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--write", action="store_true", help="Regenerate only unchanged owner-generated files")
    modes.add_argument("--check", action="store_true", help="Read-only check (default)")
    args = parser.parse_args(argv)
    try:
        result = write(args.target, args.distribution) if args.write else check(args.target, args.distribution)
        print(json.dumps(result, indent=2))
        return 0 if result["ok"] else 1
    except (ValueError, OSError) as error:
        parser.exit(2, str(error) + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
